name: 'Generate GitHub App Token'
description: 'Genera un token de acceso para una GitHub App'
inputs:
  app-id:
    description: 'ID de la GitHub App'
    required: true
  private-key:
    description: 'Clave privada de la GitHub App'
    required: true
  organization:
    description: 'Organizaci칩n donde est치 instalada la App'
    required: true
  purpose:
    description: 'Prop칩sito del token (para logging)'
    required: false
    default: 'general'
outputs:
  token:
    description: 'Token de acceso generado'
    value: ${{ steps.generate.outputs.token }}
  installation-id:
    description: 'ID de instalaci칩n de la GitHub App'
    value: ${{ steps.generate.outputs.installation_id }}
runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App Token
      id: generate
      shell: bash
      run: |
        echo "游댏 Generando token para: ${{ inputs.purpose }}"
        ${{ github.action_path }}/generate-token.sh "${{ inputs.app-id }}" "${{ inputs.private-key }}" "${{ inputs.organization }}"