name: 'Process OpenAPI Diff'
description: 'Procesa el resultado de comparación entre especificaciones OpenAPI'
inputs:
  diff-file:
    description: 'Ruta al archivo JSON con el diff'
    required: true
    default: 'diff-result.json'
  api-type:
    description: 'Tipo de API (bs, cr o ux)'
    required: true
    default: ''
  openapi-api-type:
    description: 'Tipo de API OpenAPI (bs, cr o ux)'
    required: true
    default: ''  
outputs:
  is_fix:
    description: 'Indica si los cambios son de tipo fix'
    value: ${{ steps.process.outputs.is_fix }}
  is_snapshot:
    description: 'Indica si los cambios son de tipo snapshot'
    value: ${{ steps.process.outputs.is_snapshot }}
runs:
  using: 'composite'
  steps:
    - name: Process OpenAPI diff
      id: process
      shell: bash
      env:
        OPENAPI_IGNORE_KEYS: |
          example
          summary
          description
          tags
          externalDocs
          contact
          license
          version
          security
          securitySchemes
          minimum
          default
          required
          format
          readOnly
          style
          extensions
          operationId
          components
        OPENAPI_IGNORE_KEYS_BS: |
          pattern
          example
          maxLength
          minLength
        OPENAPI_IGNORE_KEYS_CR: |
          pattern
          example
          maxLength
          minLength  
        OPENAPI_IGNORE_KEYS_UX: |
          pattern
          example
          maxLength
          minLength
        OPENAPI_REMOVE_KEYS_SNAPSHOT_BS: |
          minItems
          maxItems
          responses
        OPENAPI_REMOVE_KEYS_SNAPSHOT_CR: |
          minItems
          maxItems  
          responses
        OPENAPI_REMOVE_KEYS_SNAPSHOT_UX: |
          minItems
          maxItems
          properties
          query
          responses
      run: |
        echo "🔄 Procesando diff de OpenAPI..."
        php ${{ github.action_path }}/process-diff.php "${{ inputs.diff-file }}" "${{ inputs.api-type }}" "${{ inputs.openapi-api-type }}"